### ISSUE TITLE
Bread crumb component in Storybook

### ISSUE THREAD

**Issue by sanderdegoose** [nl-design-system/rotterdam#83] opened 2023-12-07 12:28 UTC
Bread crumbs in Figma: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?type=design&node-id=501%3A18760&mode=design&t=MMpnQo6CM31kStlb-1

**Comment by Robbert** [comment] 2023-12-09 22:18
Duplicate of #42

**Closed by Robbert** 2023-12-09 22:18 UTC
